/**
 * LEGACY DATA -> SQL
 *
 *   node scripts/legacy-to-sql.mjs
 *
 * Reads src/data/artworks.js and src/data/exhibitions.js, reports what is
 * actually in them, and writes INSERT statements for anything real.
 *
 * -----------------------------------------------------------------------------
 * WHY THIS EMITS SQL INSTEAD OF WRITING TO THE DATABASE
 * -----------------------------------------------------------------------------
 * Writing requires an admin session, which requires an email and a password.
 * Prompting for those in a terminal script means a credential in a shell
 * history and a second place to get wrong. The output goes to a file, the file
 * is read before it is run, and it is run in the same SQL Editor as the
 * migrations. Nothing is written without being looked at first.
 *
 * -----------------------------------------------------------------------------
 * WHAT COUNTS AS REAL
 * -----------------------------------------------------------------------------
 * Every entry currently in those two files is a placeholder: the ids are
 * `artwork-01`..`artwork-12`, the `type` flags on the exhibitions are set, and
 * every content field is an empty string. They were written to give the layout
 * something to lay out, not to record anything.
 *
 * An entry is emitted only if it carries at least one field a person typed —
 * a title, a year, a medium, a venue. `ratio`, `category`, `selected` and
 * `feature` do not count: they are layout settings that were filled in for
 * every placeholder and would let all twelve through.
 *
 * The `image` paths are not carried across. They point into /public, and the
 * database column is a foreign key into `media`, which describes files in
 * Supabase Storage. There is no photography in this project to move, and
 * inventing a media row for a file that does not exist would put a broken
 * image on the public site.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const OUT = 'supabase/legacy-import.sql';

const { artworks } = await import(pathToFileURL('src/data/artworks.js').href);
const { exhibitions } = await import(pathToFileURL('src/data/exhibitions.js').href);

/** Fields a person would have typed. Layout settings are not in this list. */
const ARTWORK_CONTENT = ['title', 'year', 'medium', 'dimensions', 'description', 'alt'];
const EXHIBITION_CONTENT = ['year', 'title', 'venue', 'city', 'country', 'url'];

const hasContent = (item, fields) => fields.some((f) => String(item[f] ?? '').trim() !== '');

const realArtworks = artworks.filter((a) => hasContent(a, ARTWORK_CONTENT));
const realExhibitions = exhibitions.filter((e) => hasContent(e, EXHIBITION_CONTENT));

/** Single-quote escaping. These values come from a file in the repo, not from
    a request, but a title with an apostrophe would still break the statement. */
const q = (value) => `'${String(value ?? '').replace(/'/g, "''")}'`;

/** A smallint column or NULL — `year` is a string in the legacy files. */
const num = (value) => {
  const n = Number.parseInt(String(value ?? '').trim(), 10);
  return Number.isFinite(n) ? String(n) : 'null';
};

console.log(`artworks.js      ${artworks.length} entries, ${realArtworks.length} with real content`);
console.log(`exhibitions.js   ${exhibitions.length} entries, ${realExhibitions.length} with real content`);

if (realArtworks.length === 0 && realExhibitions.length === 0) {
  console.log('');
  console.log('Nothing to migrate. Both files hold placeholders only — every content');
  console.log('field is an empty string. No SQL written.');
  console.log('');
  console.log('This is the expected result today. Re-run it if real entries are ever');
  console.log('typed into those files instead of into the admin panel.');
  process.exit(0);
}

const lines = [
  '-- Generated by scripts/legacy-to-sql.mjs — review before running.',
  `-- ${realArtworks.length} artwork(s), ${realExhibitions.length} exhibition(s).`,
  '-- Images are not included: the legacy files point at /public, and the',
  '-- database references Supabase Storage. Attach photographs in /admin.',
  '',
];

for (const a of realArtworks) {
  lines.push(
    'insert into public.artworks (slug, title, year, medium, dimensions, description, aspect_ratio, category_id, is_selected, is_featured, is_published)',
    'values (',
    `  ${q(a.id)}, ${q(a.title)}, ${num(a.year)}, ${q(a.medium)}, ${q(a.dimensions)},`,
    `  ${q(a.description)}, ${q(a.ratio || '3 / 4')},`,
    `  (select id from public.categories where slug = ${q(a.category)}),`,
    /* Imported as drafts. Publishing is a decision, and it is made in the
       panel after the record has been looked at — not by a script. */
    `  ${a.selected ? 'true' : 'false'}, ${a.feature ? 'true' : 'false'}, false`,
    ')',
    'on conflict (slug) do nothing;',
    ''
  );
}

for (const [i, e] of realExhibitions.entries()) {
  const slug = (e.title || e.venue || `exhibition-${i + 1}`)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || `exhibition-${i + 1}`;

  lines.push(
    'insert into public.exhibitions (slug, title, venue, city, country, year, exhibition_type, url, is_published)',
    'values (',
    `  ${q(slug)}, ${q(e.title)}, ${q(e.venue)}, ${q(e.city)}, ${q(e.country)},`,
    `  ${num(e.year)}, ${q(e.type ?? '')}, ${q(e.url ?? '')}, false`,
    ')',
    'on conflict (slug) do nothing;',
    ''
  );
}

writeFileSync(OUT, lines.join('\n'));

console.log('');
console.log(`Written to ${OUT}. Everything is imported as a draft —`);
console.log('read it, run it in the Supabase SQL Editor, then publish in /admin.');
